version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli # https://github.com/awslabs/serverless-application-model/issues/93
  build:
    commands:
      - sam build -t template.yml
      - sam package --template template.yml --s3-bucket "$S3_BUCKET_region1" --s3-prefix "$PROJECT_ID/builds" --output-template template-export-eu-west-1.yml --region eu-west-1
      - sam package --template template.yml --s3-bucket "$s3bucketregion2" --s3-prefix "$PROJECT_ID/builds" --output-template template-export-eu-west-2.yml --region eu-west-2

artifacts:
  type: zip
  discard-paths: yes
  files:
    # *** Change this list to reflect the per-region files generated in multiregion-build.sh
    - template-export-eu-west-1.yml
    - template-export-eu-west-2.yml
